openapi: 3.0.0
info:
  title: Coveo Passage Retrieval API
  description: A simple service to answer questions
  version: 1.0.0
servers:
  - url: ${{OPENAPI_SERVER_URL}}/api
    description: The passage api server
components:
  securitySchemes:
    apiKey:
      type: http
      scheme: bearer
paths:
  /passages:
    get:
      operationId: listPassages
      summary: List all passages
      description: Returns a list of passages with their details
      parameters:
        - name: query
          in: query
          description: A query from the user
          schema:
            type: string
          required: false
      security:
        - apiKey: []
      responses:
        "200":
          description: A list of passages related to the user query
          content:
            application/json:
              schema:
                type: object
                properties:
                  passages:
                    type: array
                    items:
                      type: object
                      properties:
                        text:
                          type: string
                          description: The text of the passage retrieved
                        relevanceScore:
                          type: number
                          format: float
                          description: The relevance score of the passage
                        document:
                          type: object
                          properties:
                            title:
                              type: string
                              description: Title of the document
                            permanentId:
                              type: string
                              description: Permanent Id of the document
                            clickableUri:
                              type: string
                              description: URL of the document
                            uniqueId:
                              type: string
                              description: Unique Id of the document